/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AttendeePickerDialog: typeof import('./src/components/planning/AttendeePickerDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DriveSyncModal: typeof import('./src/components/planning/DriveSyncModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImportMealsToShoppingModal: typeof import('./src/components/planning/ImportMealsToShoppingModal.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MealCardView: typeof import('./src/components/MealCardView.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    PlanMealDialog: typeof import('./src/components/planning/PlanMealDialog.vue')['default']
    RecipePickerDialog: typeof import('./src/components/planning/RecipePickerDialog.vue')['default']
    RecipeSourceLinkButton: typeof import('./src/components/recipes/RecipeSourceLinkButton.vue')['default']
    ReloadPrompt: typeof import('./src/components/layout/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAllergensTab: typeof import('./src/components/settings/SettingsAllergensTab.vue')['default']
    SettingsParticipantsTab: typeof import('./src/components/settings/SettingsParticipantsTab.vue')['default']
    SettingsSideDishesTab: typeof import('./src/components/settings/SettingsSideDishesTab.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
