/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--p-primary-50)',
          100: 'var(--p-primary-100)',
          200: 'var(--p-primary-200)',
          300: 'var(--p-primary-300)',
          400: 'var(--p-primary-400)',
          500: 'var(--p-primary-500)',
          600: 'var(--p-primary-600)',
          700: 'var(--p-primary-700)',
          800: 'var(--p-primary-800)',
          900: 'var(--p-primary-900)',
          950: 'var(--p-primary-950)',
          DEFAULT: '#126c4a'
        },
        surface: {
          0: 'var(--p-surface-0)',
          50: 'var(--p-surface-50)',
          100: 'var(--p-surface-100)',
          200: 'var(--p-surface-200)',
          300: 'var(--p-surface-300)',
          400: 'var(--p-surface-400)',
          500: 'var(--p-surface-500)',
          600: 'var(--p-surface-600)',
          700: 'var(--p-surface-700)',
          800: 'var(--p-surface-800)',
          900: 'var(--p-surface-900)',
          950: 'var(--p-surface-950)',
          DEFAULT: '#f9f9f7'
        },
        "background": "#f9f9f7",
        "primary-dim": "#006040",
        "error-container": "#fa746f",
        "surface-container-low": "#f3f4f2",
        "on-error": "#fff7f6",
        "tertiary-dim": "#1e5b60",
        "surface-tint": "#126c4a",
        "on-error-container": "#6e0a12",
        "surface-container": "#eceeec",
        "on-tertiary": "#e7fdff",
        "surface-dim": "#d7dbd8",
        "on-tertiary-fixed-variant": "#2b666b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#004930",
        "outline": "#777c79",
        "tertiary-fixed-dim": "#a7e1e7",
        "error-dim": "#67040d",
        "secondary-fixed-dim": "#c2daca",
        "tertiary": "#2d676c",
        "on-background": "#2f3332",
        "on-surface": "#2f3332",
        "surface-container-high": "#e6e9e6",
        "surface-bright": "#f9f9f7",
        "secondary-dim": "#42584b",
        "on-surface-variant": "#5c605e",
        "surface-variant": "#e0e3e0",
        "tertiary-container": "#b5f0f5",
        "inverse-primary": "#a7face",
        "secondary-fixed": "#d0e8d8",
        "outline-variant": "#afb3b0",
        "on-secondary-fixed-variant": "#4a6054",
        "inverse-on-surface": "#9c9d9b",
        "on-primary-fixed-variant": "#0a6947",
        "on-primary": "#e6ffee",
        "inverse-surface": "#0d0f0e",
        "on-tertiary-container": "#1f5c61",
        "surface-container-highest": "#e0e3e0",
        "on-primary-container": "#005e3e",
        "primary-fixed": "#a1f4c8",
        "secondary-container": "#d0e8d8",
        "primary-fixed-dim": "#93e5bb",
        "on-tertiary-fixed": "#00494e",
        "error": "#a83836",
        "primary-container": "#a1f4c8",
        "on-secondary-fixed": "#2f4438",
        "tertiary-fixed": "#b5f0f5",
        "on-secondary": "#e6ffee",
        "on-secondary-container": "#41574a",
        "secondary": "#4e6457"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
